# Generated by Django 3.2.5 on 2021-07-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='name',
            field=models.CharField(default='Larry', max_length=20),
            preserve_default=False,
        ),
    ]
