# Generated by Django 3.2.5 on 2021-07-25 12:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_worksheet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_time',
            field=models.TimeField(default=main.models.default_end_time),
        ),
    ]
