# Generated by Django 3.2.5 on 2021-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210723_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
