# Generated by Django 3.2.5 on 2021-07-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_worksheet_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
