# Generated by Django 3.2.5 on 2021-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='complete',
            field=models.BooleanField(db_column='Completed', default=False),
            preserve_default=False,
        ),
    ]
