# Generated by Django 3.2.5 on 2021-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_entry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
