# Generated by Django 3.2.5 on 2021-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_worksheet_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='complete',
            field=models.BooleanField(db_column='Completed', default=False),
        ),
    ]
