# Generated by Django 3.2.5 on 2021-08-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_worksheet_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='operation',
            field=models.CharField(choices=[(1, 'Orden Creada'), (2, 'En Tienda Asociada'), (3, 'Recibida en Cuyotek'), (4, 'En Mesa de Trabajo'), (5, 'Trabajo completado'), (6, 'Sin Solución'), (7, 'Lista para retirar en Cuyotek'), (8, 'Lista para retirar en Tienda Asociada'), (9, 'Es necesario contactar al cliente'), (10, 'En espera de Repuestos'), (20, 'ENTREGADA')], max_length=10),
        ),
    ]
