# Generated by Django 3.2.5 on 2021-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_entry_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='operation',
            field=models.CharField(choices=[('Proccessing', 'Proccessing'), ('Back Stock', 'Back Stock'), ('Delivery', 'Delivery'), ('Load', 'Load'), ('Scan', 'Scan'), ('R Pick', 'R Pick'), ('S Pick', 'S Pick'), ('B Pick', 'B Pick'), ('Break', 'Break'), ('Cleaning', 'Cleaning'), ('Lunch', 'Lunch'), ('Receiving', 'Receiving')], max_length=50),
        ),
    ]
