# Generated by Django 3.2.5 on 2021-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_entry_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='store',
            field=models.IntegerField(choices=[(116, '116 - Orlando'), (167, '167 - LBV')], default=116),
        ),
    ]
