# Generated by Django 3.2.5 on 2021-08-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_entry_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.AlterField(
            model_name='entry',
            name='operation',
            field=models.CharField(choices=[('Receiving', 'Receiving'), ('Processing', 'Processing'), ('Back Stocking', 'Back Stocking'), ('Picking', 'Report/Scan Picking'), ('Scanning', 'Scanning Units'), ('LOAD', 'Loading Truck'), ('DEL', 'Delivering'), ('Break', 'Break'), ('Cleaning', 'Cleaning'), ('Lunch', 'Lunch')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='store',
            field=models.IntegerField(choices=[(116, '116 - Orlando'), (167, '167 - LBV'), (215, '215 - Vineland'), (254, '254 - Footwear'), (279, '279 - Youth'), (517, '517 - Disney')], default=116),
        ),
    ]
