# Generated by Django 3.2.5 on 2021-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210812_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
    ]
